"""Initial migration

Revision ID: 06452a450b5d
Revises: 
Create Date: 2024-10-30 01:15:43.359896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06452a450b5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tgju'
    )
    op.create_table('hist_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('open', sa.BigInteger(), nullable=True),
    sa.Column('high', sa.BigInteger(), nullable=True),
    sa.Column('low', sa.BigInteger(), nullable=True),
    sa.Column('close', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tgju.instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'symbol', name='hist_price_unique_date_symbol'),
    schema='tgju'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hist_price', schema='tgju')
    op.drop_table('instrument', schema='tgju')
    # ### end Alembic commands ###
